julia fixing/main.jl "$1" "$2"

##### EXTREMELY IMPORTANT TO USE THE INVERSE COMMAS AROUND THE VARIABLES FOR JULIA TO TREAT THEM AS SINGLE ARGUMENT ENTRIES AND NOT A VECTOR OF STRINGS

# ALSO NOTE THE USE OF 1 and 2 rather than the variable names

# NEED PRECISELY THIS STRUCTURE WHEN PASSING ARGUMENTS FROM .sh to .sh scripts